### ISSUE TITLE
Panic when calling host.PlatformInformationWithContext() on Windows.

### ISSUE THREAD

**Issue by davidnewhall** [shirou/gopsutil#1315]
**Describe the bug**
Intermittent (happened once) panic when calling `host.InfoWithContext()` on Windows. [Link to gist with stack trace.](https://gist.github.com/PearsonFlyer/e4b2b83f5a213b04849f55fc0472b63c)

**To Reproduce**
I really don't know what caused this crash or how to reproduce it. It seemed to happen randomly. [My code](https://github.com/Notifiarr/notifiarr/blob/main/pkg/snapshot/snapshot.go#L152) is pretty simple. All it does is:
```go
snap.GetLocalData(ctx)
```

**Environment (please complete the following information):**
 - [x ] Windows: [paste the result of `ver`]
This was reported to me by an end user running Windows. `ver` output will be attached as soon as I receive it.

**Additional context**
Cross compiled from a Mac (x86) to Windows (amd64). Example command used to compile for windows (repeatable from Makefile):
```
GOOS=windows GOARCH=amd64 go build -o notifiarr.amd64.exe -ldflags "-w -s -X \"golift.io/version.Branch=dn2_filewatch (8404ff9)\" -X \"golift.io/version.BuildDate=2022-06-20T08:59:36Z\" -X \"golift.io/version.BuildUser=david\" -X \"golift.io/version.Revision=569\" -X \"golift.io/version.Version=0.3.1\"  "
```

I think this binary was compiled with go 1.18.0 (will confirm and update), but I've since upgraded to 1.18.3 (via brew). Here's the current `go env`.
```
$ go env
GO111MODULE="auto"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/david/Library/Caches/go-build"
GOENV="/Users/david/Library/Application Support/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/david/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/david/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.18.3/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.18.3/libexec/pkg/tool/darwin_amd64"
GOVCS=""
GOVERSION="go1.18.3"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/16/1ypyfkz12ps9bkx21hxr7j_c0000gn/T/go-build2480727710=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

I'll make a few edits to this as I receive more info.

**Comment by shirou** [comment]
Your code is very complicated because we don't know the `snap` struct. But the root cause is `host.InfoWithContext()`? Could you provide us more simple code with no other dependencies on gopsutil? Thanks.

**Comment by davidnewhall** [comment]
Sorry, I accidentally wrote the wrong function name. I edited my original post to correct it. The call my code makes is `host.InfoWithContext(ctx)` and then this is the top of the stack trace that seems most relevant:
```
unexpected fault address 0xc0014daed8
fatal error: fault
[signal 0xc0000005 code=0x1 addr=0xc0014daed8 pc=0x93ebd7]

goroutine 95253 [running]:
runtime.throw({0xde8c8c?, 0x4ff177?})
	runtime/panic.go:992 +0x76 fp=0xc000df7d28 sp=0xc000df7cf8 pc=0x4e7736
runtime.sigpanic()
	runtime/signal_windows.go:261 +0x125 fp=0xc000df7d70 sp=0xc000df7d28 pc=0x4fa725
github.com/shirou/gopsutil/v3/host.PlatformInformationWithContext({0xc01d5fe801?, 0xc000df7ed8?})
	github.com/shirou/gopsutil/v3@v3.22.5/host/host_windows.go:142 +0x97 fp=0xc000df7ea0 sp=0xc000df7d70 pc=0x93ebd7
github.com/shirou/gopsutil/v3/host.InfoWithContext({0xf4e4c0, 0xc02bc667e0})
	github.com/shirou/gopsutil/v3@v3.22.5/host/host.go:78 +0xb7 fp=0xc000df7ee8 sp=0xc000df7ea0 pc=0x93e097
github.com/Notifiarr/notifiarr/pkg/snapshot.(*Snapshot).GetLocalData(0xc000998000, {0xf4e4c0, 0xc02bc667e0})
	github.com/Notifiarr/notifiarr/pkg/snapshot/system.go:79 +0x21d fp=0xc000df7f80 sp=0xc000df7ee8 pc=0x94eafd
```

**Comment by davidnewhall** [comment]
I've had two more reports of crashes on Windows when calling `InfoWishContext()`
```
fatal error: unexpected signal during runtime execution
[signal 0xc0000005 code=0x0 addr=0xc00081e900 pc=0x642905]

goroutine 116 [running]:
runtime.throw({0xfbc4cf?, 0xc000777970?})
	runtime/panic.go:1047 +0x65 fp=0xc000777908 sp=0xc0007778d8 pc=0x5f9805
runtime.sigpanic()
	runtime/signal_windows.go:249 +0x213 fp=0xc000777950 sp=0xc000777908 pc=0x60cd93
sync.(*Pool).Get(0x183a920)
	sync/pool.go:132 +0x25 fp=0xc000777988 sp=0xc000777950 pc=0x642905
fmt.newPrinter()
	fmt/print.go:137 +0x25 fp=0xc0007779b0 sp=0xc000777988 pc=0x6b4ea5
fmt.Sprintf({0xf9893a, 0x11}, {0xc000777ae0, 0x4, 0x4})
	fmt/print.go:218 +0x36 fp=0xc000777a08 sp=0xc0007779b0 pc=0x6b5456
github.com/shirou/gopsutil/v3/host.PlatformInformationWithContext({0x19884610a01?, 0xc0007adb70?})
	github.com/shirou/gopsutil/v3@v3.22.7/host/host_windows.go:202 +0x74b fp=0xc000777b38 sp=0xc000777a08 pc=0xa9bf8b
github.com/shirou/gopsutil/v3/host.InfoWithContext({0x1103768, 0xc000c56240})
	github.com/shirou/gopsutil/v3@v3.22.7/host/host.go:78 +0xb7 fp=0xc000777b80 sp=0xc000777b38 pc=0xa9ad97
github.com/Notifiarr/notifiarr/pkg/snapshot.(*Snapshot).GetLocalData(0xc000188000, {0x1103768, 0xc000c56240})
	github.com/Notifiarr/notifiarr/pkg/snapshot/system.go:80 +0x198 fp=0xc000777c18 sp=0xc000777b80 pc=0xaac918
github.com/Notifiarr/notifiarr/pkg/snapshot.(*Config).getSnapshot(0xc0000d8230, {0x1103768, 0xc000c56240}, 0xc000188000)
	github.com/Notifiarr/notifiarr/pkg/snapshot/snapshot.go:151 +0x145 fp=0xc000777d08 sp=0xc000777c18 pc=0xaaa985
github.com/Notifiarr/notifiarr/pkg/snapshot.(*Config).GetSnapshot(0xc0000d8230)
	github.com/Notifiarr/notifiarr/pkg/snapshot/snapshot.go:142 +0x10f fp=0xc000777db0 sp=0xc000777d08 pc=0xaaa76f
github.com/Notifiarr/notifiarr/pkg/triggers/snapcron.(*cmd).sendSnapshot(0xc00008e678, {0xf89e58, 0x4})
	github.com/Notifiarr/notifiarr/pkg/triggers/snapcron/snapcron.go:93 +0x4f fp=0xc000777e68 sp=0xc000777db0 pc=0xd0138f
github.com/Notifiarr/notifiarr/pkg/triggers/snapcron.(*cmd).sendSnapshot-fm({0xf89e58?, 0xf99121?})
	<autogenerated>:1 +0x34 fp=0xc000777e90 sp=0xc000777e68 pc=0xd017b4
github.com/Notifiarr/notifiarr/pkg/triggers/common.(*Config).runEventAction(0xc00035cba0, {0xf89e58, 0x4}, 0xc0002589c0)
	github.com/Notifiarr/notifiarr/pkg/triggers/common/timers.go:97 +0x1f2 fp=0xc000777ee8 sp=0xc000777e90 pc=0xad3c92
github.com/Notifiarr/notifiarr/pkg/triggers/common.(*Config).runTimerLoop(0xc00035cba0, {0xc000356800, 0x14, 0x696c6c7574756154?}, {0xc000381500, 0x14, 0x20})
	github.com/Notifiarr/notifiarr/pkg/triggers/common/timers.go:81 +0xd3 fp=0xc000777f98 sp=0xc000777ee8 pc=0xad3873
github.com/Notifiarr/notifiarr/pkg/triggers/common.(*Config).Run.func1()
	github.com/Notifiarr/notifiarr/pkg/triggers/common/timers.go:49 +0x3e fp=0xc000777fe0 sp=0xc000777f98 pc=0xad375e
runtime.goexit()
	runtime/asm_amd64.s:1594 +0x1 fp=0xc000777fe8 sp=0xc000777fe0 pc=0x627a41
created by github.com/Notifiarr/notifiarr/pkg/triggers/common.(*Config).Run
	github.com/Notifiarr/notifiarr/pkg/triggers/common/timers.go:49 +0x8aa

goroutine 1 [syscall, locked to thread]:
fatal error: unexpected signal during runtime execution
panic during panic
[signal 0xc0000005 code=0x0 addr=0xc000bcb9c8 pc=0x61a00c]

runtime stack:
runtime.throw({0xfbc4cf?, 0x1480318?})
	runtime/panic.go:1047 +0x65 fp=0x6098fff3a0 sp=0x6098fff370 pc=0x5f9805
runtime.sigpanic()
	runtime/signal_windows.go:249 +0x213 fp=0x6098fff3e8 sp=0x6098fff3a0 pc=0x60cd93
runtime.gentraceback(0x6000000000?, 0x0?, 0xc00005c800?, 0x6098fff798?, 0x0, 0x0, 0x64, 0x0, 0x7ffca93e4fd0?, 0x0)
	runtime/traceback.go:236 +0x84c fp=0x6098fff760 sp=0x6098fff3e8 pc=0x61a00c
runtime.traceback1(0xc000052000?, 0xf89600?, 0x3?, 0xc000052000, 0x0?)
	runtime/traceback.go:846 +0x1b1 fp=0x6098fff920 sp=0x6098fff760 pc=0x61c491
runtime.traceback(...)
	runtime/traceback.go:793
runtime.tracebackothers.func1(0xc000052000)
	runtime/traceback.go:1062 +0xe5 fp=0x6098fff960 sp=0x6098fff920 pc=0x61d3e5
runtime.forEachGRace(0x6098fff9c8)
	runtime/proc.go:592 +0x4d fp=0x6098fff990 sp=0x6098fff960 pc=0x5fce4d
runtime.tracebackothers(0xc0002b24e0?)
	runtime/traceback.go:1048 +0xe5 fp=0x6098fff9f8 sp=0x6098fff990 pc=0x61d2c5
runtime.dopanic_m(0xc0002b24e0, 0x5f9875?, 0xfbc4cf?)
	runtime/panic.go:1270 +0x225 fp=0x6098fffa60 sp=0x6098fff9f8 pc=0x5fa165
runtime.fatalthrow.func1()
	runtime/panic.go:1125 +0x48 fp=0x6098fffaa0 sp=0x6098fffa60 pc=0x5f9bc8
runtime.systemstack()
	runtime/asm_amd64.s:492 +0x4e fp=0x6098fffaa8 sp=0x6098fffaa0 pc=0x62574e
```

**Comment by davidnewhall** [comment]
Might be related? https://github.com/iamacarpet/go-win64api/issues/36
