### ISSUE TITLE
Panic runtime error nil pointer on Windows for disk report

### ISSUE THREAD

**Issue by n0dev** [shirou/gopsutil#1415]
**Describe the bug**

This error came from a tool I wrote and was executed in a client environment that I don't have access to.

![image](https://user-images.githubusercontent.com/8679511/217670382-de2623d5-db85-46a4-ae7a-9ec8b30707aa.png)

**To Reproduce**

Apologize, this error came from a tool I wrote and was executed in a client environment that I don't have access to. Not sure I have the steps to reproduce as I have a feeling this is specific to what the client has configured on its Windows machine.

However it sounds like we're going through despites the error (must be something else I guess...) and `i` is still nil in `disk/disk_windows.go:107`.

```go
	for _, v := range lpBuffer {
		if v >= 65 && v <= 90 {
			i, err := getVolumeInformation(string(v), &warnings)
			if err != nil && !errors.Is(err, errDeviceNotReady) && !errors.Is(err, errInvalidDriveType) {
				continue
			}

			opts := []string{"rw"}
			if i.FileSystemFlags&fileReadOnlyVolume != 0 {
				opts = []string{"ro"}
			}
...
```

**Expected behavior**

Error to be re-thrown to parent.

**Environment (please complete the following information):**
 - [ ] Windows: Server. Not sure about the version but doubt it matters.

**Comment by shirou** [comment]
perhaps this is same as #1396. please use latest version.

**Comment by davidnewhall** [comment]
Latest version seems to do a new thing.
```
panic: send on closed channel

goroutine 138166 [running]:
github.com/shirou/gopsutil/v3/disk.PartitionsWithContext.func1()
	github.com/shirou/gopsutil/v3@v3.23.2/disk/disk_windows.go:159 +0x7e7
created by github.com/shirou/gopsutil/v3/disk.PartitionsWithContext
	github.com/shirou/gopsutil/v3@v3.23.2/disk/disk_windows.go:162 +0x1ea
```

**Comment by shirou** [comment]
Fixed by #1430. Thank you so much!
