### ISSUE TITLE
Stuck in windows syscalls after Windows 10 updates this week

### ISSUE THREAD

**Issue by tmm1** [shirou/gopsutil#1419]
cross-posting for visibility, in case someone else experiences issues and has information to add

https://github.com/golang/go/issues/58646

**Comment by tmm1** [comment]
for example we see high cpu usage and this stack trace is stuck:

```
goroutine 22 [syscall, 2208 minutes, locked to thread]:
syscall.SyscallN(0x4cdbf0?, {0xc0000a9858?, 0x0?, 0x0?})
	runtime/syscall_windows.go:557 +0x109
syscall.Syscall9(0x0?, 0x0?, 0xc000105040?, 0x200000003?, 0xc000105040?, 0xc000064500?, 0x174eaa?, 0xc0000a9910?, 0xc0000a9938?, 0xc0000a9a08, ...)
	runtime/syscall_windows.go:507 +0x78
github.com/go-ole/go-ole.invoke(0x27afe656bb8, 0x1, 0x1, {0x0, 0x0, 0x27afe65d780?})
	github.com/go-ole/go-ole@v1.2.7-0.20211215081658-ee6c8cce8e87/idispatch_windows.go:176 +0x14c5
github.com/go-ole/go-ole.(*IDispatch).Invoke(...)
	github.com/go-ole/go-ole@v1.2.7-0.20211215081658-ee6c8cce8e87/idispatch.go:27
github.com/go-ole/go-ole.(*IDispatch).InvokeWithOptionalArgs(0x206b5c7?, {0x203b5d6?, 0x0?}, 0x0?, {0x0, 0x0, 0x0})
	github.com/go-ole/go-ole@v1.2.7-0.20211215081658-ee6c8cce8e87/idispatch.go:69 +0x67
github.com/go-ole/go-ole/oleutil.CallMethod(...)
	github.com/go-ole/go-ole@v1.2.7-0.20211215081658-ee6c8cce8e87/oleutil/oleutil.go:51
github.com/yusufpapurcu/wmi.(*Client).coinitService(0x1cbbe20?, {0x0, 0x0, 0x0})
	github.com/yusufpapurcu/wmi@v1.2.3-0.20220119064729-b0230a1dc509/wmi.go:175 +0x2da
github.com/yusufpapurcu/wmi.(*Client).Query(0x172?, {0xc000224900, 0x87}, {0x1c7d740?, 0xc0007ec048?}, {0x0, 0x0, 0x0})
	github.com/yusufpapurcu/wmi@v1.2.3-0.20220119064729-b0230a1dc509/wmi.go:245 +0x296
github.com/yusufpapurcu/wmi.Query({0xc000224900?, 0x20d67f2?}, {0x1c7d740?, 0xc0007ec048?}, {0x0?, 0x5a6425?, 0xc000187320?})
	github.com/yusufpapurcu/wmi@v1.2.3-0.20220119064729-b0230a1dc509/wmi.go:77 +0x85
github.com/shirou/gopsutil/v3/internal/common.WMIQueryWithContext.func1()
	github.com/shirou/gopsutil/v3@v3.23.1/internal/common/common_windows.go:209 +0x3e
created by github.com/shirou/gopsutil/v3/internal/common.WMIQueryWithContext
	github.com/shirou/gopsutil/v3@v3.23.1/internal/common/common_windows.go:208 +0x1e5
```

I tried to replicate on my own Windows 10 and Windows 11 machines but no luck. But I have several users reporting this issue on their own machines, and it all started within the last week.

**Comment by tmm1** [comment]
cannot reproduce with go1.20
