### ISSUE TITLE
Cross compilation breaks

### ISSUE THREAD

**Issue by swynter-ladbrokes** [shirou/gopsutil#184]
When I compile on OSX for linux (using GOX) I get much strangeness

```go
func warnErr(err error) {
	if err != nil {
		fmt.Println(err)
	}
}

proc, err := process.NewProcess(pid)
if err != nil {
	fmt.Println(err)
	return
}

p := myProcess{PID: pid}

p.CmdLine, err = proc.CmdlineSlice()
warnErr(err)

p.CreateTime, err = proc.CreateTime()
warnErr(err)

p.CWD, err = proc.Cwd()
warnErr(err)

p.MemoryPercent, err = proc.MemoryPercent()
warnErr(err)

p.Name, err = proc.Name()
warnErr(err)

p.Nice, err = proc.Nice()
warnErr(err)

p.NumThreads, err = proc.NumThreads()
warnErr(err)

openFiles, err := proc.OpenFiles()
warnErr(err)
p.OpenFiles = len(openFiles)

parent, err := proc.Parent()
warnErr(err)
p.Parent = parent.Pid

p.Status, err = proc.Status()
warnErr(err)

p.Times, err = proc.Times()
warnErr(err)

p.Username, err = proc.Username()
warnErr(err)
```

```
user: LookupId not implemented on linux/amd64

open /dev/null: too many open files

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x401aa5]

goroutine 128 [running]:
panic(0x55cae0, 0xc82000a0d0)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
main.main.func1.1(0xc82000af80, 0xc820014240, 0xc800000089)
	/Users/shannon/Development/go/htop/src/htop/main.go:90 +0x3e5
created by main.main.func1
	/Users/shannon/Development/go/htop/src/htop/main.go:102 +0x88
```
nb 90 in that error corresponds with `p.Parent = parent.Pid`

The problem goes away when I compile natively on linux for linux.

**Comment by shirou** [comment]
I can build on Darwin and run Linux using this code.
https://gist.github.com/shirou/8bed639c4abd50b8aaf38a12c84f3a85

Could you teach me more specific function to fail?

And, user.LookupId can not be used when you are cross-compiling (it's means no-cgo)
see https://golang.org/src/os/user/lookup_stubs.go#L23

**Comment by freman** [comment]
You can probably close this one then.

user.LookupId is something you can't fix and p.Parent = parent.Pid is my fault, now that I've done some patching I understand how parent can be nil when there's no parent.

**Comment by shirou** [comment]
OK. so close this. Thank you.

(for later search, refs #185)
