### ISSUE TITLE
Infrequent panic in cpu.parseStatLine

### ISSUE THREAD

**Issue by razvanm** [shirou/gopsutil#424]
We just noticed an panic on a VM in AWS using a normal linux kernel. Seems like the cpu.parseStatLine makes assumptions that are not always true about the data coming from `/proc/stat`. So far we only noticed a single instance of this.

```
panic: runtime error: index out of range

goroutine 43 [running]:
grail.com/vendor/github.com/shirou/gopsutil/cpu.parseStatLine(0xe19d08, 0x0, 0x1, 0xc424d8cd20, 0x0)
	/home/pknudsgaard/src/master/go/src/grail.com/vendor/github.com/shirou/gopsutil/cpu/cpu_linux.go:173 +0x86d
grail.com/vendor/github.com/shirou/gopsutil/cpu.Times(0xb2d05e00, 0xc426b3d1f0, 0x1, 0x1, 0x0, 0x0)
	/home/pknudsgaard/src/master/go/src/grail.com/vendor/github.com/shirou/gopsutil/cpu/cpu_linux.go:53 +0x28b
grail.com/vendor/github.com/shirou/gopsutil/cpu.Percent(0xb2d05e00, 0xc425126e00, 0xd962c0, 0x0, 0x3, 0xc42686eea0, 0xc426bbe980)
	/home/pknudsgaard/src/master/go/src/grail.com/vendor/github.com/shirou/gopsutil/cpu/cpu_unix.go:61 +0x94
```

The tree we are currently using: [3562fb8aa2625aec8cac4085733a17e3da0bf5dd](https://github.com/shirou/gopsutil/tree/3562fb8aa2625aec8cac4085733a17e3da0bf5dd)

The uname:

```
Linux ip-10-0-4-218 4.4.0-1016-aws #25-Ubuntu SMP Thu Apr 20 11:34:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

What the `/proc/stat` looks like:

```
ubuntu@ip-10-0-4-218:~$ cat /proc/stat
cpu  23644 6695 4764 134931750 22115 0 473 5892 0 0
cpu0 6418 888 1230 33730755 5043 0 4 1046 0 0
cpu1 6858 4870 1632 33716510 12327 0 235 1765 0 0
cpu2 4859 622 915 33742072 2312 0 25 1546 0 0
cpu3 5507 314 986 33742411 2432 0 208 1534 0 0
intr 32552791 35 9 0 0 2335 0 3 0 2 0 0 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3107077 2985327 15704 0 6672 0 3218027 3063711 11558 0 6151 0 2160633 2194945 15838 0 6565 0 1595129 2134446 15337 0 5715 0 157 112837 717318 710764 20 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 41317767
btime 1505515383
processes 41562
procs_running 1
procs_blocked 0
softirq 5433315 0 1644387 67542 1428221 0 0 12270 1573783 0 707112
ubuntu@ip-10-0-4-218:~$ 
```

**Comment by shirou** [comment]
I can run test on AWS node and also work with your `/proc/stat` lines. How about latest code of gopsutil?

**Comment by shirou** [comment]
I close this issue. If you have something, feel free to re-open. Thank you.

**Comment by razvanm** [comment]
I think the #316 fixes this issue.

**Comment by shirou** [comment]
Thank you report!
