### ISSUE TITLE
Does the net package support centos5?

### ISSUE THREAD

**Issue by qianfangyuan** [shirou/gopsutil#585]
env:
```
LSB Version:    :core-3.1-amd64:core-3.1-ia32:core-3.1-noarch:graphics-3.1-amd64:graphics-3.1-ia32:graphics-3.1-noarch
Distributor ID: CentOS
Description:    CentOS release 5.4 (Final)
Release:        5.4
Codename:       Final
```

code:
```
	allConnection,err:=net.Connections("all")
	fmt.Println(err)
	fmt.Println(allConnection)
```

got error:
```
runtime: epollwait on fd 4 failed with 38
fatal error: runtime: netpoll failed
```

runtime stack:
```
runtime.throw(0x500d93, 0x17)
        /usr/lib/golang/src/runtime/panic.go:608 +0x72
runtime.netpoll(0x155425012af26700, 0x0)
        /usr/lib/golang/src/runtime/netpoll_epoll.go:75 +0x215
runtime.sysmon()
        /usr/lib/golang/src/runtime/proc.go:4390 +0x41b
runtime.mstart1()
        /usr/lib/golang/src/runtime/proc.go:1282 +0xe6
runtime.mstart()
        /usr/lib/golang/src/runtime/proc.go:1248 +0x6e

goroutine 1 [syscall]:
syscall.Syscall(0x0, 0x3, 0xc000262e00, 0x1000, 0xc00009c080, 0xc000262000, 0x2000)
        /usr/lib/golang/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x3, 0xc000262e00, 0x1000, 0x1000, 0xc00009c001, 0x0, 0x0)
        /usr/lib/golang/src/syscall/zsyscall_linux_amd64.go:732 +0x5a
syscall.Read(0x3, 0xc000262e00, 0x1000, 0x1000, 0xc000269620, 0x428721, 0x505ac8)
        /usr/lib/golang/src/syscall/syscall_unix.go:172 +0x49
internal/poll.(*FD).Read(0xc00019d020, 0xc000262e00, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/internal/poll/fd_unix.go:165 +0x119
os.(*File).read(0xc000098400, 0xc000262e00, 0x1000, 0x1000, 0xc000262000, 0xc00025e000, 0xe00)
        /usr/lib/golang/src/os/file_unix.go:249 +0x4e
os.(*File).Read(0xc000098400, 0xc000262e00, 0x1000, 0x1000, 0x800, 0x0, 0x0)
        /usr/lib/golang/src/os/file.go:108 +0x69
bytes.(*Buffer).ReadFrom(0xc0001b4150, 0x517740, 0xc000098400, 0x0, 0xc00004e788, 0x18)
        /usr/lib/golang/src/bytes/buffer.go:206 +0xb4
io/ioutil.readAll(0x517740, 0xc000098400, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/ioutil/ioutil.go:36 +0xb5
io/ioutil.ReadFile(0xc000238eb0, 0xd, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/golang/src/io/ioutil/ioutil.go:73 +0xd3
github.com/shirou/gopsutil/net.processInet(0xc000238eb0, 0xd, 0x100000002, 0x4fd9c3, 0x3, 0xc00008cfc0, 0x0, 0x300000002, 0xc000000480, 0xc00004e9d8, ...)
        /media/psf/GoglandProjects/FLast/src/github.com/shirou/gopsutil/net/net_linux.go:667 +0x88
github.com/shirou/gopsutil/net.statsFromInodes(0x4fdb98, 0x5, 0x0, 0xc0000c4000, 0x5, 0x5, 0xc00008cfc0, 0x203000, 0x203000, 0x38, ...)
        /media/psf/GoglandProjects/FLast/src/github.com/shirou/gopsutil/net/net_linux.go:401 +0x8ff
github.com/shirou/gopsutil/net.ConnectionsPidWithContext(0x517b00, 0xc000094010, 0x4fd990, 0x3, 0x0, 0x30, 0x4d8180, 0x201, 0x4ec3c0, 0x28)
        /media/psf/GoglandProjects/FLast/src/github.com/shirou/gopsutil/net/net_linux.go:356 +0x23c
github.com/shirou/gopsutil/net.ConnectionsPid(0x4fd990, 0x3, 0x0, 0x4116e2, 0xc00004eef0, 0xd2f7bbec, 0xe374f4596608c59a, 0x40d000)
        /media/psf/GoglandProjects/FLast/src/github.com/shirou/gopsutil/net/net_linux.go:333 +0x59
github.com/shirou/gopsutil/net.ConnectionsWithContext(0x517b00, 0xc000094010, 0x4fd990, 0x3, 0xc0000c2000, 0xc00004ef78, 0x4c07d9, 0x4dd400, 0xc00008c540)
        /media/psf/GoglandProjects/FLast/src/github.com/shirou/gopsutil/net/net_linux.go:318 +0x3d
github.com/shirou/gopsutil/net.Connections(0x4fd990, 0x3, 0xc00008c5d0, 0xc00009a180, 0xc0000a40e0, 0xc0000a40c0, 0xc0000a40a0)
        /media/psf/GoglandProjects/FLast/src/github.com/shirou/gopsutil/net/net_linux.go:314 +0x51
main.main()
        /media/psf/GoglandProjects/FLast/src/test5.go:16 +0x48
```

**Comment by shirou** [comment]
@Lomanic is right.

https://golang.org/doc/install#requirements

```
Linux 2.6.23 or later with glibc, CentOS/RHEL 5.x not supported.
```

CentOS5 is not supported by golang.
