### ISSUE TITLE
[process][darwin] Panic when calling process.CreateTime()

### ISSUE THREAD

**Issue by amitsaurav** [shirou/gopsutil#799]
Am trying to list all the processes and print the names as follows:

```
func listAllProcesses() {
  processes, err := process.Processes()
  if err != nil {
    fmt.Println("Could not get a list of processes!")
    return
  }

  for _, process := range processes {
    name, err := process.Cmdline()
    if err != nil {
      // There was an error retrieving the command line for this process. Continue to the next.
      continue
    }
    fmt.Println(name)
  }
}
```

Am  seeing panics as follows:

```
panic: runtime error: index out of range [0] with length 0

goroutine 401 [running]:
github.com/shirou/gopsutil/process.(*Process).createTimeWithContext(0xc0003ed810, 0x4e43480, 0xc0000e2020, 0x0, 0x0, 0x0)
	/Users/amitsaurav/Snapchat/Dev/go/pkg/mod/github.com/shirou/gopsutil@v2.19.9+incompatible/process/process_darwin.go:139 +0x38c
github.com/shirou/gopsutil/process.(*Process).CreateTimeWithContext(0xc0003ed810, 0x4e43480, 0xc0000e2020, 0x428c537, 0x0, 0x0)
	/Users/amitsaurav/Snapchat/Dev/go/pkg/mod/github.com/shirou/gopsutil@v2.19.9+incompatible/process/process.go:257 +0x66
github.com/shirou/gopsutil/process.(*Process).CreateTime(0xc0003ed810, 0x1, 0x0, 0x0)
	/Users/amitsaurav/Snapchat/Dev/go/pkg/mod/github.com/shirou/gopsutil@v2.19.9+incompatible/process/process.go:250 +0x43
created by github.com/shirou/gopsutil/process.NewProcess
	/Users/amitsaurav/Snapchat/Dev/go/pkg/mod/github.com/shirou/gopsutil@v2.19.9+incompatible/process/process.go:167 +0xa0
exit status 2
```

**Comment by Lomanic** [comment]
Thanks, that gives some context to https://github.com/shirou/gopsutil/pull/779 that was opened to fix this issue. I will try to reproduce thanks to your snippet.

**Comment by Lomanic** [comment]
I don't reproduce with current master on Mac OS X 10.12, could you try with the recently released v2.19.11? It includes a fix to CreateTime().

**Comment by amitsaurav** [comment]
I was on v2.19.9 where this was intermittently reproducible. I cannot reproduce it with v2.19.11. Thank you for the quick guidance!

**Comment by Lomanic** [comment]
Closing as it's already fixed then.
